export const COURT_HIERARCHY: Record<string, number> = {
  US_SUPREME_COURT: 100,
  FIFTH_CIRCUIT: 95,

  TX_SUPREME_COURT: 93,
  TX_COURT_CRIMINAL_APPEALS: 93,

  TX_COURT_OF_APPEALS: 80,
  TX_DISTRICT_COURT: 70,

  TX_COUNTY_COURT: 60,
  TX_JP_COURT: 50,
  TX_MUNICIPAL_COURT: 45
};
